// <auto-generated />
namespace MVC_Officer_Mission.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedisplayformat_of_date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedisplayformat_of_date));
        
        string IMigrationMetadata.Id
        {
            get { return "201811281324108_changedisplayformat_of_date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
