// <auto-generated />
namespace MVC_Officer_Mission.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddForeignKeyMissions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddForeignKeyMissions));
        
        string IMigrationMetadata.Id
        {
            get { return "201811131023478_AddForeignKeyMissions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
